# Generated by Django 4.2.30 on 2026-05-01 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_channel_options_alter_message_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at'], 'permissions': [('can_soft_delete_message', 'Can mark message as deleted')]},
        ),
    ]
