# Generated by Django 4.2.30 on 2026-05-02 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_customuser_blocked_channels_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_block_user', 'Can block and unblock user')]},
        ),
    ]
